name: Build Releases

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-cross:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - i686-unknown-linux-musl
          - x86_64-pc-windows-gnu
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - armv7-unknown-linux-musleabihf
          - armv7-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: rustup show

      - name: Install cross
        uses: taiki-e/install-action@cross

      - name: Build
        env:
          PKG_CONFIG_ALLOW_CROSS: "1"
        run: |
          cd build
          ./build-release.sh -t ${{ matrix.target }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/release/*
          prerelease: ${{ contains(github.ref, '-') }}
          generate_release_notes: true

  build-macos:
    name: ${{ matrix.target }}
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          rustup target add ${{ matrix.target }}
          rustup show

      - name: Install dependencies
        run: brew install openssl

      - name: Build
        run: ./build/build-host-release.sh -t ${{ matrix.target }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/release/*
          prerelease: ${{ contains(github.ref, '-') }}
          generate_release_notes: true
